### ISSUE TITLE
File Upload - Below the Fold

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#1]
It's easy to *miss* the upload area, *it's below the fold*.  

![Screenshot_2019-06-11 Document](https://user-images.githubusercontent.com/11417007/59232355-f17e3b00-8c1e-11e9-865f-88268ebc01aa.png)

The image above, shows the *visible* page.

---

Users have to scroll, to see the file upload area.

![Screenshot_2019-06-11 Document(1)](https://user-images.githubusercontent.com/11417007/59232388-11adfa00-8c1f-11e9-8332-a30effac5471.png)

**Comment by AlbertRF147** [comment]
Moved to Survey Details tab
