### ISSUE TITLE
Response Tracking - Default

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#10]
The response tracking question, should *default* to the **last** question.  

It would *normally* be the last question, unless changed by the user.

<img width="581" alt="Screen Shot 2019-06-11 at 8 50 42" src="https://user-images.githubusercontent.com/11417007/59234061-188c3b00-8c26-11e9-9d51-86aec5c24d2c.png">

**Comment by AlbertRF147** [comment]
Fixed
