### ISSUE TITLE
Skip Action - Default

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#11]
The *default* skip action *should* be the `next` question.  Again, the user would *normally* set this at the `next` question.  *Unless it's changed.*

<img width="295" alt="Screen Shot 2019-06-11 at 8 54 13" src="https://user-images.githubusercontent.com/11417007/59234195-981a0a00-8c26-11e9-8f79-394a33fc5d7a.png">

![Screenshot_2019-06-11 Document(5)](https://user-images.githubusercontent.com/11417007/59234221-bed84080-8c26-11e9-9807-a6a2ef5fa9d4.png)

**Comment by AlbertRF147** [comment]
Fixed
