### ISSUE TITLE
Typo: DTMF

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#12]
*oh no*, a typo.

<img width="393" alt="Screen Shot 2019-06-11 at 8 57 33" src="https://user-images.githubusercontent.com/11417007/59234282-019a1880-8c27-11e9-91eb-946d5e6e8dea.png">

*Dual-Tone Multi-Frequency (DTMF)*  😃

**Comment by AlbertRF147** [comment]
My bad. Fixed
