### ISSUE TITLE
Number of Questions

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#13]
Can you change the number of questions, allowing zero (`0`) as an option?

The range should be: `>=0`

<img width="284" alt="Screen Shot 2019-07-15 at 8 21 01" src="https://user-images.githubusercontent.com/11417007/61190577-86220000-a6d9-11e9-8cb7-da8217326f79.png">

Thanks

**Comment by AlbertRF147** [comment]
Sorted! Files ready for downloading and reviewing. Let me know if there is any other issue.
