### ISSUE TITLE
No Time Picker?

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#2]
In Safari, it *could* lead to bad input.

<img width="294" alt="Screen Shot 2019-06-11 at 8 12 25" src="https://user-images.githubusercontent.com/11417007/59232844-022fb080-8c21-11e9-8ab9-8e41351f851f.png">

---

Firefox *shows* seconds, but can not be modified.

<img width="300" alt="Screen Shot 2019-06-11 at 8 12 59" src="https://user-images.githubusercontent.com/11417007/59232877-2e4b3180-8c21-11e9-9b56-40cc2e7634a0.png">

---

Chrome looks OK

<img width="284" alt="Screen Shot 2019-06-11 at 8 12 44" src="https://user-images.githubusercontent.com/11417007/59232863-1d022500-8c21-11e9-9c1c-5473be336a82.png">

**Comment by AlbertRF147** [comment]
There is a time picker now
