### ISSUE TITLE
Detault Times

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#3]
You *may* use 09:00 and 21:00 as the *default* start and end times.

<img width="286" alt="Screen Shot 2019-06-11 at 8 17 19" src="https://user-images.githubusercontent.com/11417007/59232944-766a5400-8c21-11e9-8119-62b8c20696e1.png"><img width="290" alt="Screen Shot 2019-06-11 at 8 18 33" src="https://user-images.githubusercontent.com/11417007/59232969-87b36080-8c21-11e9-9553-b87cd7db2084.png">

**Comment by poing** [comment]
Seems FireFox is wants AM *-or-* PM

Please use 24-hour time formatting.

<img width="291" alt="Screen Shot 2019-06-11 at 8 44 56" src="https://user-images.githubusercontent.com/11417007/59233894-5177e000-8c25-11e9-818b-63143ab692b4.png">

**Comment by AlbertRF147** [comment]
Unfortunately, there is a bug in bulma-calendar and I could not resolve this on time. If you allow me more time I could implement an alternative time picker.
Bug: https://github.com/Wikiki/bulma-calendar/issues/163

**Comment by AlbertRF147** [comment]
Despite the bug I managed to set default times when the component is mounted. Once the bug is resolved,  start/end times will be set as properties.

**Comment by davidgil** [comment]
Hi @AlbertRF147 could you send your workaround to: https://github.com/Wikiki/bulma-calendar/issues/163

Having same issue

**Comment by affanabiyyu** [comment]
Why is this closed? I still can't set startTime in timepicker.
