### ISSUE TITLE
End Date >= Start Date

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#4]
End date datepicker should *not* allow for dates *before* the start date.

<img width="288" alt="Screen Shot 2019-06-11 at 8 19 34" src="https://user-images.githubusercontent.com/11417007/59233050-d234dd00-8c21-11e9-9ce3-b73d7c6060b7.png">

*Also, note the cropped text in the start date.*

**Comment by AlbertRF147** [comment]
I resolved this one by using date ranges (one box for start/end dates).
