### ISSUE TITLE
Default Dates

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#5]
You can set the *default* start and end dates to the *current* date.  
**or** end date *could* be `startDate + 7`, *or similar*.

<img width="287" alt="Screen Shot 2019-06-11 at 8 22 30" src="https://user-images.githubusercontent.com/11417007/59233112-132cf180-8c22-11e9-9dc2-6aec1321ebd6.png">

**Comment by AlbertRF147** [comment]
Fixed
