### ISSUE TITLE
Created Date

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#6]
The survey created date, does **not** need a date picker.  It does **not** need to be editable.  It **can** be `disabled` or even `hidden`.

<img width="288" alt="Screen Shot 2019-06-11 at 8 24 28" src="https://user-images.githubusercontent.com/11417007/59233177-61da8b80-8c22-11e9-8964-9fa1682d89eb.png">

**Comment by AlbertRF147** [comment]
Hid
