### ISSUE TITLE
Trunk Drop-Down & Channels

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#7]
Can you provide some variable `values` for the trunk to channel connection?  *Normal range is 1~100.*  Use something like `10, 25, 50, and 100` for the demo.

<img width="295" alt="Screen Shot 2019-06-11 at 8 28 32" src="https://user-images.githubusercontent.com/11417007/59233328-edecb300-8c22-11e9-973c-7bcdbefa547f.png">

---

Here's how the sliders on the current site works, using the code [here](https://gist.github.com/poing/6e15b60f29b6ba7b100bddc03b9e84cc).  `max` is based on the drop-down `value`.

<img src="https://user-images.githubusercontent.com/11417007/59076920-6433a180-8913-11e9-9c63-868d9d8c11ba.png" width="50%"><img src="https://user-images.githubusercontent.com/11417007/59076926-6ac21900-8913-11e9-9682-dc13692e5fb2.png" width="50%">
<img src="https://user-images.githubusercontent.com/11417007/59076929-6d247300-8913-11e9-9b49-37d07189684e.png" width="50%"><img src="https://user-images.githubusercontent.com/11417007/59076932-6f86cd00-8913-11e9-9554-d9cfda9e3977.png" width="50%">

**Comment by AlbertRF147** [comment]
I added `10, 25, 50, and 100` options for trunk, and made channels slider change accordingly.

**Comment by AlbertRF147** [comment]
Sorry now the slide bar is behaving oddly. Need to look into this. Will try to fix before the deadline.

**Comment by AlbertRF147** [comment]
All fixed now!
