### ISSUE TITLE
Max File Size

### ISSUE THREAD

**Issue by poing** [AlbertRF147/multistep-form-v2#9]
I am *unable* to perform some testing, due to a max file size.

<img width="259" alt="Screen Shot 2019-06-11 at 8 47 15" src="https://user-images.githubusercontent.com/11417007/59233963-a9aee200-8c25-11e9-8922-354a10dade3c.png">

---

For the *demo*, you **just** need to capture the file name for other fields.

**Comment by AlbertRF147** [comment]
Increased to 100MB
